# **PRACTICAL 1 - LEARNING PYTHON LIBRARIES**


*   **NumPy**
*   **Panda**

## **Aim**
To apply NumPy and Pandas for creating and manipulating one-dimensional (Series) and two-dimensional (DataFrame) data structures using real-world tabular data.

## **Objective**
Understand NumPy arrays and Pandas Series
Perform basic mathematical and statistical operations
Create and analyze Pandas DataFrames
Perform data selection, filtering, and basic visualization

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## **Part A: Setup and Imports**

#### A(1) Install (if not installed)

In [4]:
pip install numpy pandas

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

#### A(2) Import Required Libraries

In [5]:
import numpy as np
import pandas as pd

#### A(3) Display version

In [6]:
print('NumPy Version:', np.__version__)
print('Pandas Version:', pd.__version__)

NumPy Version: 2.0.2
Pandas Version: 2.2.2

### **Q.Bloom's Taxonomy: 5.Rememberence : Answer the below Question**

Q1. What is NumPy?

 NumPy is a Python library used for numerical computing. It provides fast array
operations and mathematical functions.

Q2. What is Pandas?

 Pandas is a Python library used for data analysis and manipulation. It provides Series and DataFrame data structures.


Q3: how to print platform (python) version?

import platform
print(platform.python_version())

## **Part B: NumPy Arrays and Pandas Series**

####B(1) Creating 1D NumPy Arrays

In [7]:
#Integer array
arr_int=np.array([1,2,3,4,5])
print(arr_int)
print(arr_int.dtype)

#Float array
arr_float=np.array([1.1,2.2,3.3,4.4,5.5])
print(arr_float)
print(arr_float.dtype)

#Mixed type array
arr_mixed=np.array([1,2.2,3,'4'])
print(arr_mixed)
print(arr_mixed.dtype)

[1 2 3 4 5]
int64
[1.1 2.2 3.3 4.4 5.5]
float64
['1' '2.2' '3' '4']
<U32

####B(2) Basic Numpy Aggregation Functions

In [8]:
A=np.array([10,20,30])
B=np.array([2,4,6])
print(A+B)
print(A-B)
print(A*B)
print(A/B)
print(A%B)

[12 24 36]
[ 8 16 24]
[ 20  80 180]
[5. 5. 5.]
[0 0 0]

####B(3) Numpy Aggregation Functions

In [9]:
Data=np.array([12,22,23,40,50])
print("Sum:", np.sum(Data))

#edit below funnctions, display with tags
print(np.mean(Data))
print(np.max(Data))
print(np.min(Data))
print(np.std(Data))

Sum: 147
29.4
50
12
13.676256797823008

####B(4) Convert NumPy Array to Pandas Series

In [10]:
Days=['Mon','Tue','Wed','Thu','Fri']
sales=np.array([120,250,470,660,880])
S=pd.Series(sales,index=Days)
print(S)

Mon    120
Tue    250
Wed    470
Thu    660
Fri    880
dtype: int64

####B(5) Access Series Elements

In [11]:
# Integer based
S[0]

# Label based
S['Wed']

/tmp/ipython-input-1409227493.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  S[0]

np.int64(470)

####B(6) Common Series Methods

In [12]:
print(S.head())
print(S.tail(2))
print(S.value_counts())
print(S.describe())

Mon    120
Tue    250
Wed    470
Thu    660
Fri    880
dtype: int64
Thu    660
Fri    880
dtype: int64
120    1
250    1
470    1
660    1
880    1
Name: count, dtype: int64
count      5.000000
mean     476.000000
std      306.153556
min      120.000000
25%      250.000000
50%      470.000000
75%      660.000000
max      880.000000
dtype: float64

## **Part C: Pandas DataFrame Basics**

####C(1) Create DataFrame from Dictionary

In [13]:
data={
    'Name': ['Gita','Sita','Mita','Nita'],
    'Maths': [78, 85, 69, 90],
    'Science': [72, 88, 75, 95]
}
df=pd.DataFrame(data)
print(df)
#or
df

   Name  Maths  Science
0  Gita     78       72
1  Sita     85       88
2  Mita     69       75
3  Nita     90       95

   Name  Maths  Science
0  Gita     78       72
1  Sita     85       88
2  Mita     69       75
3  Nita     90       95

####C(2) Create DataFrame from NumPy 2D Array

In [14]:
marks=np.array([[78,85,72],[85,90,88],[69,75,75],[90,95,90]])
df2=pd.DataFrame(marks,columns=['Maths','Science','English'])
df2
#or
#df2=pd.DataFrame(marks,columns=['Maths','Science','English'],index=['Gita','Sita','Mita','Nita'])
#df2

   Maths  Science  English
0     78       85       72
1     85       90       88
2     69       75       75
3     90       95       90

####C(3) Load Data from CSV File

In [15]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Pract_1/Churn_Modelling.csv")

####C(4) View Data

In [16]:
df.head()
df.tail()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   RowNumber    4 non-null      int64
 1   CustomerId   4 non-null      int64
 2   Surname      4 non-null      object
 3   CreditScore  4 non-null      int64
 4   Geography    4 non-null      object
 5   Gender       4 non-null      object
 6   Age          4 non-null      int64
 7   Balance      4 non-null      float64
 8   Exited       4 non-null      int64
dtypes: float64(1), int64(5), object(3)
memory usage: 420.0+ bytes

       RowNumber    CustomerId  CreditScore        Age       Balance   Exited
count   4.000000  4.000000e+00     4.000000   4.000000       4.00000  4.00000
mean    2.500000  1.565064e+07   607.000000  41.000000   60867.16500  0.50000
std     1.290994  3.569386e+04    80.899114   1.414214   76802.95427  0.57735
min     1.000000  1.561930e+07   502.000000  39.000000       0.00000  0.00000
25%     1.750000  1.563078e+07   581.500000  40.500000       0.00000  0.00000
50%     2.500000  1.564096e+07   613.500000  41.500000   41903.93000  0.50000
75%     3.250000  1.566082e+07   639.000000  42.000000  102771.09500  1.00000
max     4.000000  1.570135e+07   699.000000  42.000000  159660.80000  1.00000

####C(5) Inspect DataFrame Structure

In [17]:
print(df.shape)
print(df.columns)
print(df.index)
print(df.dtypes)
df.info()

(4, 9)
Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Balance', 'Exited'],
      dtype='object')
RangeIndex(start=0, stop=4, step=1)
RowNumber        int64
CustomerId       int64
Surname         object
CreditScore      int64
Geography       object
Gender          object
Age              int64
Balance        float64
Exited           int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   RowNumber    4 non-null      int64
 1   CustomerId   4 non-null      int64
 2   Surname      4 non-null      object
 3   CreditScore  4 non-null      int64
 4   Geography    4 non-null      object
 5   Gender       4 non-null      object
 6   Age          4 non-null      int64
 7   Balance      4 non-null      float64
 8   Exited       4 non-null      int64
dtypes: float64(1), int64(5), object(3)
memory usage: 420.0+ bytes

####C(6) Statistical Summary

In [18]:
df.describe()

       RowNumber    CustomerId  CreditScore        Age       Balance   Exited
count   4.000000  4.000000e+00     4.000000   4.000000       4.00000  4.00000
mean    2.500000  1.565064e+07   607.000000  41.000000   60867.16500  0.50000
std     1.290994  3.569386e+04    80.899114   1.414214   76802.95427  0.57735
min     1.000000  1.561930e+07   502.000000  39.000000       0.00000  0.00000
25%     1.750000  1.563078e+07   581.500000  40.500000       0.00000  0.00000
50%     2.500000  1.564096e+07   613.500000  41.500000   41903.93000  0.50000
75%     3.250000  1.566082e+07   639.000000  42.000000  102771.09500  1.00000
max     4.000000  1.570135e+07   699.000000  42.000000  159660.80000  1.00000

## **Part D: Data Selection, Analysis & Visualization**

####D(1) Select Columns

In [19]:
df['Balance']
df[['Age', 'Balance']]

   Age    Balance
0   42       0.00
1   41   83807.86
2   42  159660.80
3   39       0.00

####D(2) Select Rows

In [20]:
df.loc[0]
df.loc[0:4]
df.loc[2, ['Surname', 'Age', 'Balance', 'Exited']]

Surname        Onio
Age              42
Balance    159660.8
Exited            1
Name: 2, dtype: object

####D(3) Using iloc (integer based)

In [21]:
df.iloc[0]
df.iloc[0:5, 0:4]
df.iloc[-3:]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Balance,Exited
1,2,15647311,Hill,608,Spain,Female,41,83807.86,0
2,3,15619304,Onio,502,France,Female,42,159660.80,1
3,4,15701354,Boni,699,Germany,Male,39,0.00,0

####D(4) Filter Rows with Salary

In [22]:
df[df['Balance'] > 100000]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Balance,Exited
2,3,15619304,Onio,502,France,Female,42,159660.8,1

####D(5)  NumPy Vs Pandas Functions

In [23]:
np.mean(df['Balance'])
df['Balance'].mean()

np.max(df['Balance'])
df['Balance'].max()

159660.8

####D(6) Add New Calculated Vectorized (column)

In [24]:
# Vectorized column: Balance per Age
df['BalancePerAge'] = (df['Balance'] / df['Age']).round(2)

# Vectorized conditional column: Risk Category based on CreditScore
df['RiskCategory'] = np.where(df['CreditScore'] >= 700, 'Low Risk', 'High Risk')

print("DataFrame with new calculated columns (first 6 rows):")
print(df[['Surname', 'Age', 'Balance', 'CreditScore', 'BalancePerAge', 'RiskCategory']].head(6))
print()

print("RiskCategory value_counts():")
print(df['RiskCategory'].value_counts())

DataFrame with new calculated columns (first 6 rows):
    Surname  Age    Balance  CreditScore  BalancePerAge RiskCategory
0  Hargrave   42       0.00          619           0.00    High Risk
1      Hill   41   83807.86          608        2044.09    High Risk
2      Onio   42  159660.80          502        3801.45    High Risk
3      Boni   39       0.00          699           0.00    High Risk

RiskCategory value_counts():
RiskCategory
High Risk    4
Name: count, dtype: int64

## **Part E: Saving & Exploring Data**

####E(1) Save to csv

In [25]:
df.to_csv('Churn_Modelling_Updated.csv', index=False)

####E(2) Reload & Verify

In [27]:
df_reloaded = pd.read_csv('Churn_Modelling_Updated.csv')
df_reloaded.head()
df_reloaded.tail()
df_reloaded.info()
df_reloaded.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   RowNumber      4 non-null      int64
 1   CustomerId     4 non-null      int64
 2   Surname        4 non-null      object
 3   CreditScore    4 non-null      int64
 4   Geography      4 non-null      object
 5   Gender         4 non-null      object
 6   Age            4 non-null      int64
 7   Balance        4 non-null      float64
 8   Exited         4 non-null      int64
 9   BalancePerAge  4 non-null      float64
 10  RiskCategory   4 non-null      object
dtypes: float64(2), int64(5), object(4)
memory usage: 484.0+ bytes

,RowNumber,CustomerId,CreditScore,Age,Balance,Exited,BalancePerAge
count,4.000000,4.000000e+00,4.000000,4.000000,4.00000,4.00000,4.000000
mean,2.500000,1.565064e+07,607.000000,41.000000,60867.16500,0.50000,1461.385000
std,1.290994,3.569386e+04,80.899114,1.414214,76802.95427,0.57735,1833.643146
min,1.000000,1.561930e+07,502.000000,39.000000,0.00000,0.00000,0.000000
25%,1.750000,1.563078e+07,581.500000,40.500000,0.00000,0.00000,0.000000
50%,2.500000,1.564096e+07,613.500000,41.500000,41903.93000,0.50000,1022.045000
75%,3.250000,1.566082e+07,639.000000,42.000000,102771.09500,1.00000,2483.430000
max,4.000000,1.570135e+07,699.000000,42.000000,159660.80000,1.00000,3801.450000

## **Assignment**

In [29]:
import pandas as pd

df_students = pd.DataFrame({
    'Name': ['Gita','Sita','Mita','Nita'],
    'Maths': [78, 85, 69, 90],
    'Science': [72, 88, 75, 95]
})
# Daily Sales Series
pd.Series([100,200,150,300], index=['Mon','Tue','Wed','Thu'])

# Students Marks Analysis
df_students.describe()

# Numeric Column Analysis
df['Balance'].describe()

# Save & Clean
df.dropna()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Balance,Exited,BalancePerAge,RiskCategory
0,1,15634602,Hargrave,619,France,Female,42,0.00,1,0.00,High Risk
1,2,15647311,Hill,608,Spain,Female,41,83807.86,0,2044.09,High Risk
2,3,15619304,Onio,502,France,Female,42,159660.80,1,3801.45,High Risk
3,4,15701354,Boni,699,Germany,Male,39,0.00,0,0.00,High Risk

# **Few Conceptual Questions & RTO**

1. What is the difference between NumPy array and Pandas Series?

   NumPy arrays are unlabeled, while Pandas Series are labeled.

2. Why is vectorized operation faster in Pandas?

   They avoid loops and use optimized C-based operations.

3. What is the use of describe() function?

   It provides statistical summary of numeric data.

# Learning Outcome

Through this practical, I learned how to create and manipulate NumPy arrays, Pandas Series, and DataFrames. I performed data selection, filtering, statistical analysis, and file operations. I am confident in applying these concepts independently.